import "./global.css";
import Link from "next/link";

export const metadata = {
	title: "Word Snake v1",
	description: "Generated by Next.js",
};

export default function RootLayout({ children }) {
	return (
		<html lang="en">
			<body>
				<nav>
					<Link href="/" className="navName">Word Snake v1</Link>
					<ul className="navMenu">
						<li>
							<Link href="/about" className="navMenu__link">About</Link>
						</li>
					</ul>
				</nav>
				{children}
			</body>
		</html>
	);
}
