import "./global.css";
import Link from "next/link";

export const metadata = {
	title: "Word Snake v1",
	description: "Generated by Next.js",
};

export default function RootLayout({ children }) {
	return (
		<html lang="en">
			<body>
				<nav>
					<span>Word Snake v1</span>
					<ul>
						<li>
							<Link href="/">Home</Link>
						</li>
						<li>
							<Link href="/play">Play</Link>
						</li>
						<li>
							<Link href="/result">Result</Link>
						</li>
						<li>
							<Link href="/about">About</Link>
						</li>
					</ul>
				</nav>
				{children}
			</body>
		</html>
	);
}
