export const metadata = {
	title: "Word Snake v1",
	description: "Generated by Next.js",
};

export default function RootLayout({ children }) {
	return (
		<html lang="en">
			<body>
        <div>
          <h1>Word Snake v1</h1>
          <ul>
            <li>Home</li>
            <li>About</li>
          </ul>
        </div>
        {children}</body>
		</html>
	);
}
